# Generated by Django 5.2.1 on 2026-05-05 15:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.CharField(max_length=80, unique=True)),
                ('start_time', models.TimeField()),
                ('late_after_minutes', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['classroom'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, unique=True)),
                ('student_code', models.CharField(max_length=50, unique=True)),
                ('classroom', models.CharField(max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name_snapshot', models.CharField(max_length=120)),
                ('classroom_snapshot', models.CharField(blank=True, max_length=80)),
                ('recognized_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('confidence_score', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('present', 'Present'), ('late', 'Retard'), ('unknown', 'Inconnu')], max_length=12)),
                ('source', models.CharField(default='camera', max_length=20)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='attendance.student')),
            ],
            options={
                'ordering': ['-recognized_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='students')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='attendance.student')),
            ],
            options={
                'ordering': ['student__full_name', 'created_at'],
            },
        ),
    ]
