# Generated by Django 5.2.1 on 2026-05-05 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=150, verbose_name='Intitule')),
                ('faculty', models.CharField(blank=True, choices=[('info', 'Informatique'), ('sci', 'Sciences'), ('med', 'Medecine / Sante'), ('droit', 'Droit'), ('eco', 'Economie / Gestion'), ('lettres', 'Lettres & Sciences Humaines'), ('ing', 'Ingenierie'), ('autre', 'Autre')], default='', max_length=20, verbose_name='Faculte')),
                ('professor', models.CharField(blank=True, default='', max_length=120, verbose_name='Professeur')),
                ('credits', models.PositiveIntegerField(default=3, verbose_name='Credits')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='UnknownFaceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='unknown_faces/')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(default='photo', max_length=20)),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='student',
            name='faculty',
            field=models.CharField(blank=True, choices=[('info', 'Informatique'), ('sci', 'Sciences'), ('med', 'Medecine / Sante'), ('droit', 'Droit'), ('eco', 'Economie / Gestion'), ('lettres', 'Lettres & Sciences Humaines'), ('ing', 'Ingenierie'), ('autre', 'Autre')], default='', max_length=20, verbose_name='Faculte'),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Telephone'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='source',
            field=models.CharField(default='photo', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('late', 'Retard'), ('absent', 'Absent'), ('unknown', 'Inconnu')], max_length=12),
        ),
        migrations.AlterField(
            model_name='student',
            name='classroom',
            field=models.CharField(max_length=80, verbose_name='Classe / Groupe'),
        ),
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(max_length=120, unique=True, verbose_name='Nom complet'),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Matricule'),
        ),
        migrations.CreateModel(
            name='CourseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('start_time', models.TimeField(verbose_name='Heure debut')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Heure fin')),
                ('room', models.CharField(blank=True, default='', max_length=80, verbose_name='Salle')),
                ('late_after_minutes', models.PositiveIntegerField(default=15, verbose_name='Retard apres (min)')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('closed', models.BooleanField(default=False, verbose_name='Session fermee')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='attendance.course')),
            ],
            options={
                'ordering': ['-date', '-start_time'],
            },
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='course_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='attendance.coursesession'),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='attendance.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='attendance.student')),
            ],
            options={
                'ordering': ['student__full_name'],
                'unique_together': {('student', 'course')},
            },
        ),
    ]
