# Generated by Django 5.2.1 on 2026-05-05 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_course_unknownfacelog_student_date_of_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('location', models.CharField(blank=True, default='', max_length=150, verbose_name='Emplacement')),
                ('camera_type', models.CharField(choices=[('webcam', 'Webcam navigateur'), ('usb', 'Camera USB (serveur)'), ('rtsp', 'Camera IP (RTSP)')], default='webcam', max_length=10, verbose_name='Type')),
                ('source', models.CharField(blank=True, default='', help_text="Vide = webcam par defaut. '0','1' = index USB. 'rtsp://...' = camera IP.", max_length=300, verbose_name='Source')),
                ('resolution_w', models.PositiveIntegerField(default=640, verbose_name='Largeur (px)')),
                ('resolution_h', models.PositiveIntegerField(default=480, verbose_name='Hauteur (px)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='trainingphoto',
            name='face_detected',
            field=models.BooleanField(default=True, verbose_name='Visage detecte'),
        ),
        migrations.AddField(
            model_name='trainingphoto',
            name='trained_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'entrainement"),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='attendance.camera'),
        ),
        migrations.AddField(
            model_name='unknownfacelog',
            name='camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.camera'),
        ),
    ]
