# Generated by Django 5.2.1 on 2026-05-16 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_camera_trainingphoto_face_detected_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la classe')),
                ('niveau', models.CharField(help_text='Ex: L1, L2, L3, Master 1, G3', max_length=50, verbose_name='Niveau')),
                ('option', models.CharField(blank=True, default='', max_length=100, verbose_name='Option / Specialite')),
                ('annee_academique', models.CharField(default='2025-2026', max_length=20, verbose_name='Annee academique')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
                'ordering': ['niveau', 'nom'],
            },
        ),
        migrations.AddField(
            model_name='coursesession',
            name='status',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('ouvert', 'Ouvert'), ('ferme', 'Ferme')], default='en_attente', max_length=12, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('late', 'Retard'), ('absent', 'Absent'), ('unknown', 'Inconnu'), ('refused', 'Refuse (hors horaire)')], max_length=12),
        ),
        migrations.AlterField(
            model_name='coursesession',
            name='closed',
            field=models.BooleanField(default=False, verbose_name='Session fermee (legacy)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='classroom',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Classe (legacy)'),
        ),
        migrations.AddField(
            model_name='student',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='attendance.classe', verbose_name='Classe'),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour_semaine', models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi')], verbose_name='Jour de la semaine')),
                ('heure_debut', models.TimeField(verbose_name='Heure de debut')),
                ('heure_fin', models.TimeField(verbose_name='Heure de fin')),
                ('tolerance_retard_minutes', models.PositiveIntegerField(default=15, help_text="Nombre de minutes apres le debut avant d'etre marque en retard", verbose_name='Tolerance retard (min)')),
                ('salle', models.CharField(blank=True, default='', max_length=80, verbose_name='Salle')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='attendance.classe', verbose_name='Classe')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='attendance.course', verbose_name='Cours')),
            ],
            options={
                'verbose_name': 'Horaire',
                'verbose_name_plural': 'Horaires',
                'ordering': ['jour_semaine', 'heure_debut'],
            },
        ),
        migrations.AddField(
            model_name='coursesession',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='attendance.schedule', verbose_name='Horaire source'),
        ),
    ]
