# Generated by Django 5.2.1 on 2026-05-16 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_classe_coursesession_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modifie_par', models.CharField(default='admin', max_length=120, verbose_name='Modifie par')),
                ('ancienne_valeur', models.CharField(max_length=20, verbose_name='Ancienne valeur')),
                ('nouvelle_valeur', models.CharField(max_length=20, verbose_name='Nouvelle valeur')),
                ('raison', models.TextField(blank=True, default='', verbose_name='Raison / Justificatif')),
                ('date_modification', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Journal d'audit",
                'verbose_name_plural': "Journal d'audit",
                'ordering': ['-date_modification'],
            },
        ),
        migrations.CreateModel(
            name='JourFerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='Motif / Description')),
                ('date', models.DateField(unique=True, verbose_name='Date')),
                ('type_jour', models.CharField(choices=[('ferie', 'Jour ferie'), ('vacances', 'Vacances / Conge'), ('suspension', 'Suspension de cours')], default='ferie', max_length=20, verbose_name='Type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Jour ferie',
                'verbose_name_plural': 'Jours feries',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80, unique=True, verbose_name='Nom de la salle')),
                ('batiment', models.CharField(blank=True, default='', max_length=80, verbose_name='Batiment')),
                ('capacite', models.PositiveIntegerField(default=30, verbose_name='Capacite (etudiants)')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Salle',
                'verbose_name_plural': 'Salles',
                'ordering': ['batiment', 'nom'],
            },
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='excuse_notes',
            field=models.TextField(blank=True, default='', verbose_name='Notes justificatif'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='excuse_reason',
            field=models.CharField(blank=True, choices=[('', '—'), ('maladie', 'Maladie'), ('mission', 'Mission officielle'), ('deuil', 'Deuil'), ('autorisation', 'Autorisation speciale'), ('autre', 'Autre')], default='', max_length=20, verbose_name='Type de justificatif'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='modified_by',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Modifie par'),
        ),
        migrations.AddField(
            model_name='coursesession',
            name='minutes_avant_cours',
            field=models.PositiveIntegerField(default=10, verbose_name='Fenetre pre-cours (min)'),
        ),
        migrations.AddField(
            model_name='coursesession',
            name='motif_annulation',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name="Motif d'annulation"),
        ),
        migrations.AddField(
            model_name='schedule',
            name='minutes_avant_cours',
            field=models.PositiveIntegerField(default=10, help_text='Nombre de minutes avant le debut ou la detection est autorisee', verbose_name='Fenetre pre-cours (min)'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('late', 'Retard'), ('absent', 'Absent'), ('excuse', 'Excuse / Justifie'), ('unknown', 'Inconnu'), ('refused', 'Refuse (hors horaire)')], max_length=12),
        ),
        migrations.AlterField(
            model_name='classe',
            name='niveau',
            field=models.CharField(help_text='Ex: L1, L2, L3, G3, Master 1', max_length=50, verbose_name='Niveau'),
        ),
        migrations.AlterField(
            model_name='coursesession',
            name='status',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('ouvert', 'Ouvert'), ('ferme', 'Ferme'), ('annule', 'Annule')], default='en_attente', max_length=12, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='tolerance_retard_minutes',
            field=models.PositiveIntegerField(default=15, help_text="Minutes apres le debut avant d'etre marque en retard", verbose_name='Tolerance retard (min)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='classroom',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Classe (snapshot)'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['student'], name='attendance__student_bf8a5d_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['course_session'], name='attendance__course__890295_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['status'], name='attendance__status_741eb8_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['recognized_at'], name='attendance__recogni_daff1a_idx'),
        ),
        migrations.AddIndex(
            model_name='coursesession',
            index=models.Index(fields=['date'], name='attendance__date_5afb96_idx'),
        ),
        migrations.AddIndex(
            model_name='coursesession',
            index=models.Index(fields=['status'], name='attendance__status_0f9648_idx'),
        ),
        migrations.AddIndex(
            model_name='coursesession',
            index=models.Index(fields=['course', 'date'], name='attendance__course__97c44a_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['student_code'], name='attendance__student_52589a_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['classe'], name='attendance__classe__7dcfd0_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['is_active'], name='attendance__is_acti_2f65d1_idx'),
        ),
        migrations.AddField(
            model_name='attendanceauditlog',
            name='attendance_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='attendance.attendancerecord'),
        ),
        migrations.AddField(
            model_name='camera',
            name='salle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cameras', to='attendance.salle', verbose_name='Salle associee'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='salle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='attendance.salle', verbose_name='Salle'),
        ),
    ]
