# Generated by Django 5.2.1 on 2026-05-16 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_attendanceauditlog_jourferie_salle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retard_minutes', models.PositiveIntegerField(default=15, help_text="Minutes apres le debut du cours avant d'etre marque en retard.", verbose_name='Tolerance retard (min)')),
                ('ouverture_avant_minutes', models.PositiveIntegerField(default=10, help_text='Minutes avant le debut ou la detection est acceptee.', verbose_name='Fenetre pre-cours (min)')),
                ('cooldown_detection_minutes', models.PositiveIntegerField(default=5, help_text='Intervalle minimal entre deux detections du meme etudiant dans la meme session.', verbose_name='Cooldown anti-doublon (min)')),
                ('seuil_distance_lbph', models.FloatField(default=60.0, help_text='Seuil de distance LBPH. En dessous = reconnu. Plus strict = valeur plus faible.', verbose_name='Distance LBPH max (seuil)')),
                ('seuil_alerte_absences', models.PositiveIntegerField(default=3, help_text="Nombre d'absences a partir duquel l'alerte apparait sur le tableau de bord.", verbose_name='Seuil alerte absences')),
                ('filtrer_par_classe', models.BooleanField(default=True, help_text='Ne reconnaitre que les etudiants de la classe liee a la session active.', verbose_name='Filtrer par classe')),
                ('archiver_evenements_bruts', models.BooleanField(default=True, help_text='Journaliser chaque detection dans FaceDetectionEvent pour audit et debug.', verbose_name='Archiver evenements bruts')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration systeme',
                'verbose_name_plural': 'Configuration systeme',
            },
        ),
        migrations.CreateModel(
            name='FaceDetectionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etape', models.CharField(choices=[('detecte', 'Visage detecte'), ('reconnu', 'Identite probable'), ('enregistre', 'Presence enregistree'), ('refuse', 'Refuse (hors horaire)'), ('hors_cl', 'Hors classe (filtre)'), ('inconnu', 'Visage inconnu'), ('doublon', 'Doublon (deja marque)'), ('trop_tot', 'Trop tot (avant fenetre)')], max_length=10)),
                ('confiance', models.FloatField(default=0.0, verbose_name='Confiance (%)')),
                ('source', models.CharField(default='live', max_length=20)),
                ('raison', models.CharField(blank=True, default='', max_length=200, verbose_name='Raison')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.camera')),
                ('course_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detection_events', to='attendance.coursesession')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detection_events', to='attendance.student')),
            ],
            options={
                'verbose_name': 'Evenement de detection',
                'verbose_name_plural': 'Evenements de detection',
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['detected_at'], name='attendance__detecte_0c2e68_idx'), models.Index(fields=['etape'], name='attendance__etape_0c7070_idx'), models.Index(fields=['student', 'detected_at'], name='attendance__student_0b1a6a_idx')],
            },
        ),
    ]
