# Generated by Django 5.2.1 on 2026-05-16 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_systemconfig_facedetectionevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolDayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Journee scolaire', max_length=100)),
                ('heure_ouverture', models.TimeField(default='06:30', verbose_name='Ouverture portail')),
                ('heure_debut_cours', models.TimeField(default='07:00', verbose_name='Debut cours (arrivee = Present)')),
                ('heure_limite_arrivee', models.TimeField(default='07:30', verbose_name='Heure limite arrivee (apres = Retard)')),
                ('heure_fin_cours', models.TimeField(default='15:30', verbose_name='Fin des cours')),
                ('heure_sortie_precoce', models.TimeField(default='15:00', verbose_name='Seuil sortie precoce (avant = Sortie precoce)')),
                ('heure_fermeture', models.TimeField(default='17:00', verbose_name='Fermeture portail')),
                ('lundi', models.BooleanField(default=True, verbose_name='Lundi')),
                ('mardi', models.BooleanField(default=True, verbose_name='Mardi')),
                ('mercredi', models.BooleanField(default=True, verbose_name='Mercredi')),
                ('jeudi', models.BooleanField(default=True, verbose_name='Jeudi')),
                ('vendredi', models.BooleanField(default=True, verbose_name='Vendredi')),
                ('samedi', models.BooleanField(default=False, verbose_name='Samedi')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration journee scolaire',
                'verbose_name_plural': 'Configuration journee scolaire',
            },
        ),
        migrations.AddField(
            model_name='camera',
            name='zone_type',
            field=models.CharField(choices=[('check_in', 'Entree ecole (CHECK-IN)'), ('check_out', 'Sortie ecole (CHECK-OUT)'), ('monitoring', 'Surveillance (monitoring)')], default='monitoring', help_text="CHECK-IN = enregistre l'arrivee des eleves. CHECK-OUT = enregistre la sortie. MONITORING = surveillance sans presence.", max_length=12, verbose_name='Zone'),
        ),
        migrations.CreateModel(
            name='DailyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('heure_entree', models.TimeField(blank=True, null=True, verbose_name="Heure d'arrivee")),
                ('heure_sortie', models.TimeField(blank=True, null=True, verbose_name='Heure de sortie')),
                ('status', models.CharField(choices=[('present', 'Present'), ('retard', 'En retard'), ('absent', 'Absent'), ('sorti', 'Sorti'), ('sortie_precoce', 'Sortie precoce'), ('excuse', 'Excuse / Justifie')], default='absent', max_length=20, verbose_name='Statut')),
                ('modified_by', models.CharField(blank=True, default='', max_length=120, verbose_name='Modifie par')),
                ('excuse_reason', models.CharField(blank=True, choices=[('', '— Aucun justificatif —'), ('maladie', 'Maladie'), ('mission', 'Mission officielle'), ('deuil', 'Deuil'), ('autorisation', 'Autorisation parentale'), ('autre', 'Autre')], default='', max_length=50, verbose_name='Type justificatif')),
                ('excuse_notes', models.TextField(blank=True, default='', verbose_name='Notes justificatif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camera_entree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_ins', to='attendance.camera', verbose_name='Camera entree')),
                ('camera_sortie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_outs', to='attendance.camera', verbose_name='Camera sortie')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_attendances', to='attendance.student', verbose_name='Eleve')),
            ],
            options={
                'verbose_name': 'Presence journaliere',
                'verbose_name_plural': 'Presences journalieres',
                'ordering': ['-date', 'student__full_name'],
                'indexes': [models.Index(fields=['date'], name='attendance__date_370344_idx'), models.Index(fields=['student', 'date'], name='attendance__student_ed8b4b_idx'), models.Index(fields=['status'], name='attendance__status_ac56c5_idx')],
                'unique_together': {('student', 'date')},
            },
        ),
    ]
