# Generated by Django 5.2.1 on 2026-05-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_daily_attendance_school_day_config_camera_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='detection_mode',
            field=models.CharField(choices=[('recognition', 'Reconnaissance active (RECOGNITION)'), ('monitoring_only', 'Surveillance seulement (MONITORING)'), ('off', 'Desactivee (OFF)')], default='recognition', help_text='RECOGNITION = IA active. MONITORING = flux video sans IA. OFF = camera inactive.', max_length=16, verbose_name='Mode detection'),
        ),
        migrations.AddField(
            model_name='camera',
            name='error_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Nb erreurs'),
        ),
        migrations.AddField(
            model_name='camera',
            name='fps_estimate',
            field=models.FloatField(default=0.0, verbose_name='FPS estime'),
        ),
        migrations.AddField(
            model_name='camera',
            name='frames_processed',
            field=models.PositiveIntegerField(default=0, verbose_name='Images traitees'),
        ),
        migrations.AddField(
            model_name='camera',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='En ligne'),
        ),
        migrations.AddField(
            model_name='camera',
            name='last_error',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Derniere erreur'),
        ),
        migrations.AddField(
            model_name='camera',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dernier contact'),
        ),
    ]
