# Generated by Django 5.2.1 on 2026-05-16 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_camera_detection_mode_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='seuil_confiance_haute',
            field=models.FloatField(default=40.0, help_text='Distance LBPH EN DESSOUS de ce seuil : reconnaissance directe sans revue. Recommande : 35-45.', verbose_name='Seuil haute confiance (auto-accepte)'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='seuil_distance_lbph',
            field=models.FloatField(default=65.0, help_text='Distance LBPH EN DESSOUS de ce seuil : mis en file de revue (LOW_CONFIDENCE). Au-dessus : INCONNU. Recommande : 55-70.', verbose_name='Seuil limite (zone de doute)'),
        ),
        migrations.CreateModel(
            name='RecognitionReviewQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_proposed', models.FloatField(default=0.0, verbose_name='Score confiance (0-100, plus haut = meilleur)')),
                ('distance_lbph', models.FloatField(default=0.0, verbose_name='Distance LBPH brute')),
                ('confidence_second', models.FloatField(default=0.0, verbose_name='Score second candidat')),
                ('technical_status', models.CharField(choices=[('low_confidence', 'Faible confiance (LOW_CONFIDENCE)'), ('multiple_match', 'Correspondance ambigue (MULTIPLE_MATCH)')], default='low_confidence', max_length=20, verbose_name='Statut technique')),
                ('daily_date', models.DateField(blank=True, null=True, verbose_name='Date (presence journaliere)')),
                ('face_image', models.ImageField(blank=True, null=True, upload_to='review_queue/%Y/%m/%d/', verbose_name='Capture du visage')),
                ('detected_at', models.DateTimeField(auto_now_add=True, verbose_name='Detecte le')),
                ('source', models.CharField(default='live', max_length=20, verbose_name='Source')),
                ('status', models.CharField(choices=[('pending', 'En attente de revue'), ('validated', 'Valide — presence enregistree'), ('rejected', 'Rejete — pas de presence')], default='pending', max_length=12, verbose_name='Statut revue')),
                ('reviewed_by', models.CharField(blank=True, default='', max_length=120, verbose_name='Revise par')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Revise le')),
                ('review_notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_queue_items', to='attendance.camera', verbose_name='Camera')),
                ('course_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_queue_items', to='attendance.coursesession', verbose_name='Session de cours')),
                ('second_candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_second_proposals', to='attendance.student', verbose_name='Second candidat')),
                ('student_proposed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_proposals', to='attendance.student', verbose_name="Etudiant propose par l'IA")),
            ],
            options={
                'verbose_name': 'Ticket de revue reconnaissance',
                'verbose_name_plural': 'File de revue reconnaissance',
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['status'], name='attendance__status_b48807_idx'), models.Index(fields=['detected_at'], name='attendance__detecte_8a9992_idx')],
            },
        ),
    ]
