# Generated by Django 5.2.1 on 2026-05-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_review_queue_and_confidence_tiers'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_by', models.CharField(default='system', max_length=150, verbose_name='Declenche par')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Debut')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fin')),
                ('duration_seconds', models.FloatField(default=0.0, verbose_name='Duree (sec)')),
                ('nb_students', models.PositiveIntegerField(default=0, verbose_name='Eleves traites')),
                ('nb_photos', models.PositiveIntegerField(default=0, verbose_name='Photos utilisees')),
                ('nb_skipped_blurry', models.PositiveIntegerField(default=0, verbose_name='Photos floues ignorees')),
                ('success', models.BooleanField(default=True, verbose_name='Succes')),
                ('error_message', models.TextField(blank=True, default='', verbose_name="Message d'erreur")),
            ],
            options={
                'verbose_name': 'Historique entrainement',
                'verbose_name_plural': 'Historique entrainements',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='anonyme', max_length=150, verbose_name='Utilisateur')),
                ('action', models.CharField(choices=[('login', 'Connexion'), ('logout', 'Deconnexion'), ('create', 'Creation'), ('update', 'Modification'), ('delete', 'Suppression'), ('train', 'Entrainement IA'), ('recognize', 'Reconnaissance'), ('config', 'Configuration'), ('camera', 'Camera'), ('review', 'Revue'), ('export', 'Export'), ('access', 'Acces'), ('error', 'Erreur'), ('other', 'Autre')], default='other', max_length=20, verbose_name='Action')),
                ('object_type', models.CharField(blank=True, choices=[('student', 'Eleve'), ('camera', 'Camera'), ('classe', 'Classe'), ('course', 'Cours'), ('session', 'Session'), ('user', 'Utilisateur'), ('config', 'Configuration'), ('model', 'Modele IA'), ('attendance', 'Presence'), ('review', 'Revue'), ('photo', 'Photo'), ('system', 'Systeme')], default='', max_length=20, verbose_name='Type objet')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID objet')),
                ('object_repr', models.CharField(blank=True, default='', max_length=255, verbose_name='Description objet')),
                ('details', models.TextField(blank=True, default='', verbose_name='Details')),
                ('ip_address', models.CharField(blank=True, default='', max_length=45, verbose_name='Adresse IP')),
                ('success', models.BooleanField(default=True, verbose_name='Succes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date/heure')),
            ],
            options={
                'verbose_name': 'Journal systeme',
                'verbose_name_plural': 'Journal systeme',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action'], name='attendance__action_d5e0bf_idx'), models.Index(fields=['user'], name='attendance__user_ee6bcf_idx'), models.Index(fields=['created_at'], name='attendance__created_6155db_idx'), models.Index(fields=['object_type'], name='attendance__object__0154cd_idx')],
            },
        ),
    ]
