# Generated by Django 5.2.1 on 2026-06-02 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_system_log_training_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', models.BinaryField(verbose_name='Vecteur (256 floats)')),
                ('angle_tag', models.CharField(blank=True, default='', max_length=20, verbose_name='Angle')),
                ('score_qualite', models.FloatField(default=0.0, verbose_name='Score qualité (netteté)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Empreinte faciale',
                'verbose_name_plural': 'Empreintes faciales',
                'ordering': ['student__full_name', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('enseignant', 'Enseignant'), ('secretariat', 'Secrétariat')], default='secretariat', max_length=20, verbose_name='Rôle')),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
                'verbose_name_plural': 'Profils utilisateurs',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='adresse',
            field=models.TextField(blank=True, default='', verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='student',
            name='annee_scolaire',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Année scolaire'),
        ),
        migrations.AddField(
            model_name='student',
            name='date_inscription',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'inscription"),
        ),
        migrations.AddField(
            model_name='student',
            name='lieu_naissance',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Lieu de naissance'),
        ),
        migrations.AddField(
            model_name='student',
            name='nom',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Nom de famille'),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_nom',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Nom du parent / tuteur'),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_telephone',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Téléphone du parent'),
        ),
        migrations.AddField(
            model_name='student',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to='students/profil/', verbose_name='Photo de profil'),
        ),
        migrations.AddField(
            model_name='student',
            name='post_nom',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Post-nom'),
        ),
        migrations.AddField(
            model_name='student',
            name='prenom',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Prénom(s)'),
        ),
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='student',
            name='sexe',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], default='', max_length=1, verbose_name='Sexe'),
        ),
        migrations.AddField(
            model_name='student',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif'), ('transfere', 'Transféré'), ('suspendu', 'Suspendu'), ('exclu', 'Exclu'), ('diplome', 'Diplômé'), ('inactif', 'Inactif')], default='actif', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='trainingphoto',
            name='angle_tag',
            field=models.CharField(blank=True, choices=[('face', 'Face'), ('gauche', 'Gauche'), ('droite', 'Droite'), ('incline', 'Légèrement incliné'), ('autre', 'Autre')], default='', max_length=20, verbose_name='Angle'),
        ),
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(max_length=240, unique=True, verbose_name='Nom complet'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Téléphone élève'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['statut'], name='attendance__statut_2bd38c_idx'),
        ),
        migrations.AddField(
            model_name='faceembedding',
            name='photo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='attendance.trainingphoto', verbose_name='Photo source'),
        ),
        migrations.AddField(
            model_name='faceembedding',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_embeddings', to='attendance.student', verbose_name='Élève'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
