# Generated by Django 5.2.1 on 2026-06-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_secpresence_extended_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemconfig',
            name='seuil_confiance_haute',
            field=models.FloatField(default=58.0, help_text='Distance EN DESSOUS de ce seuil : reconnaissance directe sans revue. Recommande : 55-62.', verbose_name='Seuil haute confiance (auto-accepte)'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='seuil_distance_lbph',
            field=models.FloatField(default=75.0, help_text='Distance EN DESSOUS de ce seuil : mis en file de revue. Au-dessus : INCONNU. Recommande : 70-80.', verbose_name='Seuil limite (zone de doute)'),
        ),
    ]
